### ISSUE TITLE
Extend to support adaboost?

### ISSUE THREAD

**Issue by jasopolis** [rivolli/utiml#10]
Would there be some way to support an adaboost implementation as a base classifiers?

(Sorry, I just noticed xgboost is already supported, apologies)

**Comment by rivolli** [comment]
It is already supported, just use "XGB" as base algorithm and make sure you
have the xgboost package installed

Cheers
Adriano Rívolli

**Comment by jasopolis** [comment]
Thanks Adriano, I was just confused since it wasn't in the overview vignette. I've submitted a PR at #11 to fix this, if you'd like to help avoid confusion for other users in the future!

Thanks again for putting this together, it's been really helpful for our team. :)
