### ISSUE TITLE
# 3 Pre-processing

### ISSUE THREAD

**Issue by ajcanepa** [rivolli/utiml#6]
Following the vignettes (.Rmd) reaching the point Nº 3 (Pre-processing), at line 113 the function `fill_sparce_mldata()`  cannot be found. Any idea where is the function since it's part of the package?, is something related with the installation of the development vs CRAN version?

**Comment by rivolli** [comment]
I am sorry, the vignette was wrong, the correct name of the method is
*fill_sparse_mldata*
I fixed the vignette.


Thank you for your report

Adriano Rívolli
