### ISSUE TITLE
# 5. Classification Methods --> Dependency with "C5.0"

### ISSUE THREAD

**Issue by ajcanepa** [rivolli/utiml#7]
Following the Vignette (*.Rmd) file, at line 264 when attempting to perform (# Ensemble with 5 models using 60% of sampling and 75% of attributes) the function `ebr()` try to use a dependency that seems not be updated which is the [C50: C5.0 Decision Trees and Rule-Based Models](https://cran.r-project.org/package=C50).
Is that the package that must be uploaded first?
Thanks!

**Comment by rivolli** [comment]
The utiml does not install automatically the base classifiers, so you will
need to install manually according to your preferences.

You can install the C5.0 with the command *install.packages("C50")*
Cheers

Adriano Rívolli
