### ISSUE TITLE
How to create the data structure mdata as toyml?

### ISSUE THREAD

**Issue by vtshen** [rivolli/utiml#8]
In the example of mlknn,
```
fit = mlknn(mdata=toyml, k = 10, s = 1, distance = "euclidean")
```
the data set toyml has the class 
```
> class(toyml)
[1] "mldr"
```
I have my own data X and Y, is there a function to convert my data to the class mldr?

```
> names(toyml)
[1] "name"              "dataset"           "attributesIndexes"
[4] "attributes"        "labels"            "labelsets"        
[7] "measures"
```

I tried the website http://sites.labic.icmc.usp.br/mldatagen/#outputArea but it did not produce the data set with class mldf

Thanks

**Comment by rivolli** [comment]
Hi you can transform your own data into an mldr object using the function
mldr_from_dataframe (https://rdrr.io/cran/mldr/man/mldr_from_dataframe.html)
It is available at mldr package, however, if you installed utiml the mldr
is also installed.

Cheers,
Adriano Rívolli da Silva
