### ISSUE TITLE
How to add a classifier?

### ISSUE THREAD

**Issue by ElenJ** [rivolli/utiml#9]
Hi Adriano,
I would like to add the regularized random Forest from the RRF package to your awesome utiml package.
I changed the source of the model such that (and simply run is at "RF": 

mltrain.baseRF <- function(object, ...) {
  if (requireNamespace("randomForest", quietly = TRUE)) {
    traindata <- object$data[, -object$labelindex]
    labeldata <- object$data[, object$labelindex]
    model <- RRF::RRF(traindata, labeldata, ...) #modified to take RRF
  }
  else {
    stop(paste("There are no installed package 'randomForest' to use",
               "randomForest classifier as base method"))
  }
  model
}

However, this does not change the base.learner taken neither the results. What am I missing?
Best regards,
Elena

**Comment by rivolli** [comment]
Hello Elena,  thank you for using utiml
It is still in development and we accept any collaboration :)

Anyway, It should work but I am not sure why it didn't work.
So I tested an alternative version and it worked, I hope it can help you

library(utiml)

mltrain.baseRRF <- function(object, ...) {
  traindata <- object$data[, -object$labelindex]
  labeldata <- object$data[, object$labelindex]
  RRF::RRF(traindata, labeldata, ...) #modified to take RRF
}

mlpredict.RRF <- function(model, newdata, ...) {
result <- stats::predict(model, newdata, type = "prob", ...)
  prediction <- colnames(result)[apply(result, 1, which.max)]
  data.frame(
    prediction = prediction,
    probability = result[cbind(rownames(newdata), prediction)],
    row.names = rownames(newdata)
  )
}

model <- br(toyml, "RFF")
head(predict(model, toyml))

So with this, you can use a new base algorithm "RFF"
Any additional doubts let me know

Best regards,
Adriano Rívolli

**Comment by ElenJ** [comment]
Hi Adriano,
thanks a lot for the quick reply! Indeed, it worked! I suppose the difference was, I just replaced RF with RRF in the model call, but left mltrain.baseRF (not RRF) and called 
model <- br(toyml, "RF"), which apparently, was wrong. 
I suppose, the "baseX" is wired somewhere into the code.
Anyway, it works now.
All the best,
Elena
